CREATE TABLE DEPARTMENTS
   (	DEPARTMENT_ID NUMBER(4,0),
	DEPARTMENT_NAME VARCHAR2(30) CONSTRAINT DEPT_NAME_NN NOT NULL ENABLE,
	MANAGER_ID NUMBER(6,0),
	LOCATION_ID NUMBER(4,0),
	 CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
	  REFERENCES LOCATIONS (LOCATION_ID) ENABLE,
	 CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_ID)
	  REFERENCES EMPLOYEES (EMPLOYEE_ID) ENABLE
   ) ;
  CREATE UNIQUE INDEX DEPT_ID_PK ON DEPARTMENTS (DEPARTMENT_ID)
  ;
ALTER TABLE DEPARTMENTS ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID)
  USING INDEX DEPT_ID_PK  ENABLE;
CREATE UNIQUE INDEX DEPT_ID_PK ON DEPARTMENTS (DEPARTMENT_ID)
  ;
CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS (LOCATION_ID)
  ;

