CREATE TABLE EMPLOYEES
   (	EMPLOYEE_ID NUMBER(6,0),
	FIRST_NAME VARCHAR2(20),
	LAST_NAME VARCHAR2(25) CONSTRAINT EMP_LAST_NAME_NN NOT NULL ENABLE,
	EMAIL VARCHAR2(25) CONSTRAINT EMP_EMAIL_NN NOT NULL ENABLE,
	PHONE_NUMBER VARCHAR2(20),
	HIRE_DATE DATE CONSTRAINT EMP_HIRE_DATE_NN NOT NULL ENABLE,
	JOB_ID VARCHAR2(10) CONSTRAINT EMP_JOB_NN NOT NULL ENABLE,
	SALARY NUMBER(8,2),
	COMMISSION_PCT NUMBER(2,2),
	MANAGER_ID NUMBER(6,0),
	DEPARTMENT_ID NUMBER(4,0),
	 CONSTRAINT EMP_SALARY_MIN CHECK (salary > 0) ENABLE,
	 CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL)
  USING INDEX  ENABLE,
	 CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
	  REFERENCES DEPARTMENTS (DEPARTMENT_ID) ENABLE,
	 CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID)
	  REFERENCES JOBS (JOB_ID) ENABLE,
	 CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID)
	  REFERENCES EMPLOYEES (EMPLOYEE_ID) ENABLE
   ) ;
  CREATE UNIQUE INDEX EMP_EMP_ID_PK ON EMPLOYEES (EMPLOYEE_ID)
  ;
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID)
  USING INDEX EMP_EMP_ID_PK  ENABLE;
CREATE UNIQUE INDEX EMP_EMP_ID_PK ON EMPLOYEES (EMPLOYEE_ID)
  ;
CREATE INDEX EMP_JOB_IX ON EMPLOYEES (JOB_ID)
  ;
CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES (MANAGER_ID)
  ;
CREATE INDEX EMP_NAME_IX ON EMPLOYEES (LAST_NAME, FIRST_NAME)
  ;
CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES (DEPARTMENT_ID)
  ;

