CREATE TABLE JOBS
   (	JOB_ID VARCHAR2(10),
	JOB_TITLE VARCHAR2(35) CONSTRAINT JOB_TITLE_NN NOT NULL ENABLE,
	MIN_SALARY NUMBER(6,0),
	MAX_SALARY NUMBER(6,0)
   ) ;
  CREATE UNIQUE INDEX JOB_ID_PK ON JOBS (JOB_ID)
  ;
ALTER TABLE JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
  USING INDEX JOB_ID_PK  ENABLE;
CREATE UNIQUE INDEX JOB_ID_PK ON JOBS (JOB_ID)
  ;

