CREATE TABLE LOCATIONS
   (	LOCATION_ID NUMBER(4,0),
	STREET_ADDRESS VARCHAR2(40),
	POSTAL_CODE VARCHAR2(12),
	CITY VARCHAR2(30) CONSTRAINT LOC_CITY_NN NOT NULL ENABLE,
	STATE_PROVINCE VARCHAR2(25),
	COUNTRY_ID CHAR(2),
	 CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
	  REFERENCES COUNTRIES (COUNTRY_ID) ENABLE
   ) ;
  CREATE UNIQUE INDEX LOC_ID_PK ON LOCATIONS (LOCATION_ID)
  ;
ALTER TABLE LOCATIONS ADD CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID)
  USING INDEX LOC_ID_PK  ENABLE;
CREATE UNIQUE INDEX LOC_ID_PK ON LOCATIONS (LOCATION_ID)
  ;
CREATE INDEX LOC_CITY_IX ON LOCATIONS (CITY)
  ;
CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS (STATE_PROVINCE)
  ;
CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS (COUNTRY_ID)
  ;

