CREATE TABLE REGIONS
   (	REGION_ID NUMBER CONSTRAINT REGION_ID_NN NOT NULL ENABLE,
	REGION_NAME VARCHAR2(25)
   ) ;
  CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID)
  ;
ALTER TABLE REGIONS ADD CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID)
  USING INDEX REG_ID_PK  ENABLE;
CREATE UNIQUE INDEX REG_ID_PK ON REGIONS (REGION_ID)
  ;

